project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/',admin.site.urls),
    path('', include(('chatbot_project.urls2','chatbot_project'),namespace = 'chatbot_project')),
    path('', include(('trained.urls','trained'),namespace = 'trained')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trained/urls.py
from django.contrib import admin
from django.urls import path 
from . import views

urlpatterns = [
    #path('admin/', views.index,name = 'index'),
    path('train/', views.menu,name='menu'),
    path('trained/', views.train_chat,name='train_chat'),
    path('train2/', views.create_node,name='node'),
    path('edit_menu/<str:pk>/', views.edit_menu, name='edit_menu'),
    path('delete_menu/<str:pk>/', views.delete_menu, name='delete_menu'),
    path('my_view/<str:pk>/', views.my_view, name='my_view'),
    path('add_submenu/<str:pk>/', views.add_submenu, name='add_submenu'),
    #path('showing/', views.train_chat, name='train_chat')
    path('index/', views.upload_picture, name='first_page'),
    path('user/', views.user_register, name='register_user'),
    path('user_show/', views.show_query, name='show_query'),
    path('home_new/', views.home, name='home'),
    path('chatbot_view/', views.chatbot_view, name='chatbot_view'),
    path('chatbot_details/', views.chatbot_details, name='chatbot_details'),
    path('chatbot_trainer/', views.chatbot_trainer, name='chatbot_trainer'),
    path('query_form/', views.query_form, name='query_form'),



    
    ]

trained/models.py
from django.db import models

from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

class Menuss(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    answer = models.CharField(max_length=50, unique=True,null= True,blank= True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['name']

class Node(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,)
    answer = models.CharField(max_length=100,null=True, blank=True)
    def __str__(self):
        return self.name

# class ActivityLog(models.Model):
#     activity = models.CharField(max_length=255)
#     timestamp = models.DateTimeField(auto_now_add=True)
#     ip_address = models.GenericIPAddressField()
#     device = models.CharField(max_length=100)
#     location = models.CharField(max_length=100)
    
#     def __str__(self):
#         return self.activity

class Admin_panel(models.Model):
    heading = models.CharField(max_length=15,null=True,blank=True)
    image =  models.ImageField(upload_to='uploads/',blank=True)
    welcome_msg =  models.TextField(blank=True,null=True)
    color_theme = models.CharField(max_length = 16,null=True,blank=True)
    def __str__(self):
        return self.heading

class user_panel(models.Model):
    input_label = models.CharField(max_length=60,null=True,blank=True)
    input_type = models.CharField(max_length=78, null = True, blank = True)
    parent_id = models.IntegerField(default=0, blank=True, null=True)
    def __str__(self):
        return self.input_label

from django.db import models

class MyModel(models.Model):
    char_field = models.CharField(max_length=100)
    text_field = models.TextField()
    boolean_field = models.BooleanField()
    integer_field = models.IntegerField()
    float_field = models.FloatField()
    decimal_field = models.DecimalField(max_digits=10, decimal_places=2)
    date_field = models.DateField()
    datetime_field = models.DateTimeField()
    email_field = models.EmailField()
    url_field = models.URLField()
    file_field = models.FileField(upload_to='uploads/')
    image_field = models.ImageField(upload_to='images/')
    class Meta:
        managed = False
        db_table = 'my_table_name'

trained/forms.py
from django import forms
from .models import *

class MenuForm(forms.ModelForm):
    class Meta:
        model = Menuss
        fields = ('name', 'answer')

from django import forms

from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = forms.ModelChoiceField(queryset=Menuss.objects.all())
    class Meta:
        model = Menuss
        fields = ('name', 'parent', 'answer')

       
from django import forms
from .models import Node

class NodeForm(forms.ModelForm):
    parent = forms.ModelChoiceField(queryset=Node.objects.all())

    class Meta:
        model = Node
        fields = ['name', 'parent','answer']
from django import forms
from .models import *

class PictureUploadForm(forms.ModelForm):
    class Meta:
        model = Admin_panel
        fields = ['heading','image','welcome_msg']

trained/views.py
from django.shortcuts import render,get_object_or_404
import re
from django.http import HttpRequest, JsonResponse
from django.shortcuts import render, HttpResponse,redirect
import random
import json
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from .models import *
import logging
from django.db import models
from django.core.management import call_command
from django.apps import apps
from .dynamic_models import *
from trained.dynamic_models import create_dynamic_model
from django.db import connection
from django.http import HttpResponse
from .models import *

# from .dynamic_models import create_dynamic_model
# def activity_logging(activity):
#     activity = activity
#     ip_address = request.META.get('REMOTE_ADDR')
#         if ip_address:
#             response = requests.get(f'https://api.ipgeolocation.io/ipgeo?apiKey=YOUR_API_KEY&ip={ip_address}')
#             if response.status_code == 200:
#                 location_data = response.json()
#                 location_info = f"{location_data['city']}, {location_data['country_name']}"
#                 location = location_info
#     activity_log = ActivityLog(activity=activity, ip_address=ip_address)


# This retrieves a Python logging instance (or creates it)
logger = logging.getLogger(__name__)
# Create your views here.
from django.shortcuts import render,redirect
# from .forms import *

def menu(request):
    if request.method == 'POST':
        form = NewCommentForm(request.POST)
        if form.is_valid():
            form.save() 
    else:
        form = NewCommentForm()

    return render(request, 'trained/train1.html', {'form': form})


from django.shortcuts import render
from .forms import *
from .models import *

def create_node(request):
    if request.method == 'POST':
        form = NodeForm(request.POST)
        if form.is_valid():
            form.save()
        data = Node.objects.all()
    else:
        form = NodeForm()
        data = Node.objects.all()

    nodes = Node.objects.all()
    context = {
        'form': form,
        'nodes': nodes,
        'data': data
    }
    return render(request, 'trained/train2.html', context)

def edit_menu(request, pk):
    book = get_object_or_404(Node, id=pk)
    form = NodeForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        # return redirect('/trained/')
     
    return render(request, 'trained/edit_menu.html', {'form': form, 'book': book})

def delete_menu(request, pk):
    my_object = get_object_or_404(Node, id=pk)

    if request.method == 'POST':
        # Delete the object
        my_object.delete()
        return redirect('/trained/')
    return render(request, 'trained/train2.html')

def train_chat(request):

    if request.method == 'POST':
        menu = request.POST.get('menu').lower()
        my_model_instance = Node(name=menu)
        my_model_instance.save()
        #print(menu)

    data  = Node.objects.filter(parent__isnull=True)
    context = {'data': data}
        
    return render(request, 'trained/train.html',context)

def my_view(request,pk):
    parent = Node.objects.get(id=pk)
    queryset = Node.objects.filter(parent__isnull=False, parent=parent)
    data = []
    for model in queryset:
        data.append(model.name)
    return JsonResponse(data, safe=False)

def add_submenu(request,pk):
    if request.method == 'POST':
        name = request.POST.get('name')
        answer = request.POST.get('answer')
        parent = Node.objects.get(id=pk)
        data = {
        'name': name,
        'answer': answer,
        'parent': parent,
        }
        my_object = Node.objects.create(**data)
    parent = Node.objects.get(id=pk)
    queryset = Node.objects.filter(parent__isnull=False, parent=parent)
    # data = []
    # for model in queryset:
    #     data.append(model.name)
    return render(request, 'trained/show.html',{'data': queryset})

# def train_chat(request):   
#     return render(request, 'trained/chatbot-trainer.html')
from django.shortcuts import render
from .forms import *

def upload_picture(request):
    if request.method == 'POST':
        form = PictureUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            
    else:
        form = PictureUploadForm()
    
    my_model = Admin_panel.objects.first()
    return render(request, 'trained/index2.html', {'form': form})

from django.db import models

  # Define the DynamicModel at the module level

def user_register(request):
        if request.method == 'POST':
            input_types = {}
            column_names = []

            for field_name, field_value in request.POST.items():
                if field_name.endswith('_input_type'):
                    x = field_name.split('_')
                    field_name = x[0]  # Remove '_input_type' suffix

                    input_type = field_value
                    input_types[field_name] = input_type
                    column_names.append(field_name)
                    input_type = field_value
                    input_types[field_name] = input_type
                    my_object = user_panel.objects.create(input_label=field_name, input_type=input_type, parent_id=1)

            # Generate the CREATE TABLE SQL statement
            table_name = MyModel._meta.db_table
            columns = ', '.join([f"{column} VARCHAR(255)" for column in column_names])  # Modify the VARCHAR(255) to match your field types
            sql = f"CREATE TABLE {table_name} (id INT AUTO_INCREMENT PRIMARY KEY, {columns})"

            # Execute the SQL statement
            with connection.cursor() as cursor:
                cursor.execute(sql)

        return render(request, 'trained/user_register.html')

def show_query(request):
    my_view = user_panel.objects.filter(parent_id=1).order_by('-id')
    my_view = my_view.reverse()
    if request.method == 'POST':
        # Retrieve form data
        table_name = MyModel._meta.db_table
        form_data = {}
        with connection.cursor() as cursor:
            cursor.execute(f"DESCRIBE {table_name}")
            columns = [column[0] for column in cursor.fetchall()]
        for column in columns:
            value = request.POST.get(column, '')
            print(value)
            form_data[column] = value

        # Save form data to the dynamically created table
        with connection.cursor() as cursor:
            columns = ', '.join(form_data.keys())
            values = ', '.join([f"'{value}'" for value in form_data.values()])
            sql = f"INSERT INTO {table_name} ({columns}) VALUES ({values})"
            cursor.execute(sql)
        
    return render(request, 'trained/show_query.html', {'my_view': my_view})
    
def home(request):
    return render(request, 'new_folder/index.html')
def chatbot_view(request):
    return render(request, 'new_folder/chatbot.html')
def chatbot_details(request):
    return render(request, 'new_folder/chatbot_details.html')
def chatbot_trainer(request):
    return render(request, 'new_folder/chatbot_trainer.html')
def query_form(request):
    return render(request, 'new_folder/query_form.html')

trained/templates/new_folder/base.html
<head>
    {%load static%}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link href="documentation/img/vert-favicon.png" rel="icon">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'VertAge_CahtBot/assets/vendor/bootstrap/css/bootstrap.min.css'%}">
    <link href="{% static 'VertAge_CahtBot/assets/vendor/fonts/circular-std/style.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'VertAge_CahtBot/assets/libs/css/style.css'%}">
    <link rel="stylesheet" href="{% static 'VertAge_CahtBot/assets/vendor/fonts/fontawesome/css/fontawesome-all.css'%}">
    <link rel="stylesheet" href="{% static 'VertAge_CahtBot/assets/vendor/charts/chartist-bundle/chartist.css'%}">
    <link rel="stylesheet" href="{% static 'VertAge_CahtBot/assets/vendor/charts/morris-bundle/morris.css'%}">
    <link rel="stylesheet" href="{% static 'VertAge_CahtBot/assets/vendor/fonts/material-design-iconic-font/css/materialdesignicons.min.css'%}">
    <link rel="stylesheet" href="{% static 'VertAge_CahtBot/assets/vendor/charts/c3charts/c3.css'%}">
    <link rel="stylesheet" href="{% static 'VertAge_CahtBot/assets/vendor/fonts/flag-icon-css/flag-icon.min.css'%}">
    <title>Vert-Age</title>
</head>

<body>
 <!-- Optional JavaScript -->
    <!-- jquery 3.3.1 -->
    <script src="VertAge_CahtBot/assets/vendor/jquery/jquery-3.3.1.min.js"></script>
    <!-- bootstap bundle js -->
    <script src="VertAge_CahtBot/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <!-- slimscroll js -->
    <script src="VertAge_CahtBot/assets/vendor/slimscroll/jquery.slimscroll.js"></script>
    <!-- main js -->
    <script src="VertAge_CahtBot/assets/libs/js/main-js.js"></script>
    <!-- chart chartist js -->
    <script src="VertAge_CahtBot/assets/vendor/charts/chartist-bundle/chartist.min.js"></script>
    <!-- sparkline js -->
    <script src="VertAge_CahtBot/assets/vendor/charts/sparkline/jquery.sparkline.js"></script>
    <!-- morris js -->
    <script src="VertAge_CahtBot/assets/vendor/charts/morris-bundle/raphael.min.js"></script>
    <script src="VertAge_CahtBot/assets/vendor/charts/morris-bundle/morris.js"></script>
    <!-- chart c3 js -->
    <script src="VertAge_CahtBot/assets/vendor/charts/c3charts/c3.min.js"></script>
    <script src="VertAge_CahtBot/assets/vendor/charts/c3charts/d3-5.4.0.min.js"></script>
    <script src="VertAge_CahtBot/assets/vendor/charts/c3charts/C3chartjs.js"></script>
    <script src="VertAge_CahtBot/assets/libs/js/dashboard-ecommerce.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- ============================================================== -->
    <!-- main wrapper -->
    <!-- ============================================================== -->
    <div class="dashboard-main-wrapper">
        <!-- ============================================================== -->
        <!-- navbar -->
        <!-- ============================================================== -->
        <div class="dashboard-header">
            <nav class="navbar navbar-expand-lg bg-white fixed-top">

                <a href="index.html">
                    <img src="documentation/img/vert-logo.png" alt="" class="logo-brand">
                </a>

                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto navbar-right-top">
                        <li class="nav-item">
                            <div id="custom-search" class="top-search-bar">
                                <input class="form-control" type="text" placeholder="Search..">
                            </div>
                        </li>
                        <li class="nav-item dropdown notification">
                            <a class="nav-link nav-icons" href="#" id="navbarDropdownMenuLink1" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false"><i class="fas fa-fw fa-bell"></i> <span
                                    class="indicator"></span></a>
                        </li>
                        <li class="nav-item dropdown connection">
                            <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false"> <i class="fas fa-fw fa-th"></i> </a>
                        </li>
                        <li class="nav-item dropdown nav-user">
                            <a class="nav-link nav-user-img" href="#" id="navbarDropdownMenuLink2"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img
                                    src="assets/images/avatar-1.jpg" alt="" class="user-avatar-md rounded-circle"></a>
                            <div class="dropdown-menu dropdown-menu-right nav-user-dropdown"
                                aria-labelledby="navbarDropdownMenuLink2">
                                <div class="nav-user-info">
                                    <h5 class="mb-0 text-white nav-user-name">Person Name</h5>
                                    <span class="status"></span><span class="ml-2">Available</span>
                                </div>
                                <a class="dropdown-item" href="#"><i class="fas fa-user mr-2"></i>Account</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-cog mr-2"></i>Setting</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-power-off mr-2"></i>Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- ============================================================== -->
        <!-- end navbar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- left sidebar -->
        <!-- ============================================================== -->
        <div class="nav-left-sidebar sidebar-dark">
            <div class="menu-list">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="d-xl-none d-lg-none" href="#">Dashboard</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav flex-column">
                            <li class="nav-divider">
                                Menu
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link active" href="{% url 'trained:home'%}" aria-expanded="false" data-target="#submenu-1"
                                    aria-controls="submenu-1"><i class="fa fa-fw fa-user-circle"></i>Dashboard <span
                                        class="badge badge-success">6</span></a>
                                <div id="submenu-1" class="collapse submenu" style="">

                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'trained:chatbot_view'%}" aria-expanded="false" data-target="#submenu-2"
                                    aria-controls="submenu-2"><i class="fa fa-fw fa-rocket"></i>ChatBot</a>

                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'trained:chatbot_trainer'%}" aria-expanded="false" data-target="#submenu-3"
                                    aria-controls="submenu-3"><i class="fas fa-fw fa-chart-pie"></i>ChatBot Trainer</a>

                            </li>
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'trained:chatbot_details'%}" aria-expanded="false"
                                    data-target="#submenu-4" aria-controls="submenu-4"><i
                                        class="fas fa-fw fa-file"></i>ChatBot Details</a>

                            </li>
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'trained:query_form'%}" aria-expanded="false"
                                    data-target="#submenu-4" aria-controls="submenu-4"><i
                                        class="fab fa-fw fa-wpforms"></i>Query Form</a>

                            </li>

                        </ul>
                    </div>
                </nav>
            </div>
        </div>
</body>