project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/',admin.site.urls),
    path('', include(('chatbot_project.urls2','chatbot_project'),namespace = 'chatbot_project')),
    path('', include(('trained.urls','trained'),namespace = 'trained')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trained/urls.py
from django.contrib import admin
from django.urls import path 
from . import views

urlpatterns = [
    #path('admin/', views.index,name = 'index'),
    path('train/', views.menu,name='menu'),
    path('trained/', views.train_chat,name='train_chat'),
    path('train2/', views.create_node,name='node'),
    path('edit_menu/<str:pk>/', views.edit_menu, name='edit_menu'),
    path('delete_menu/<str:pk>/', views.delete_menu, name='delete_menu'),
    path('my_view/<str:pk>/', views.my_view, name='my_view'),
    path('add_submenu/<str:pk>/', views.add_submenu, name='add_submenu'),
    #path('showing/', views.train_chat, name='train_chat')
    path('index/', views.upload_picture, name='first_page'),
    path('user/', views.user_register, name='register_user'),
    path('user_show/', views.show_query, name='show_query'),
    path('home_new/', views.home, name='home'),
    path('chatbot_view/', views.chatbot_view, name='chatbot_view'),
    path('chatbot_details/', views.chatbot_details, name='chatbot_details'),
    path('chatbot_trainer/', views.chatbot_trainer, name='chatbot_trainer'),
    path('query_form/', views.query_form, name='query_form'),



    
    ]

trained/models.py
from django.db import models

from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

class Menuss(MPTTModel):
    name = models.CharField(max_length=50, unique=True)
    answer = models.CharField(max_length=50, unique=True,null= True,blank= True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['name']

class Node(models.Model):
    name = models.CharField(max_length=100)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True,)
    answer = models.CharField(max_length=100,null=True, blank=True)
    def __str__(self):
        return self.name

# class ActivityLog(models.Model):
#     activity = models.CharField(max_length=255)
#     timestamp = models.DateTimeField(auto_now_add=True)
#     ip_address = models.GenericIPAddressField()
#     device = models.CharField(max_length=100)
#     location = models.CharField(max_length=100)
    
#     def __str__(self):
#         return self.activity

class Admin_panel(models.Model):
    heading = models.CharField(max_length=15,null=True,blank=True)
    image =  models.ImageField(upload_to='uploads/',blank=True)
    welcome_msg =  models.TextField(blank=True,null=True)
    color_theme = models.CharField(max_length = 16,null=True,blank=True)
    def __str__(self):
        return self.heading

class user_panel(models.Model):
    input_label = models.CharField(max_length=60,null=True,blank=True)
    input_type = models.CharField(max_length=78, null = True, blank = True)
    parent_id = models.IntegerField(default=0, blank=True, null=True)
    def __str__(self):
        return self.input_label

from django.db import models

class MyModel(models.Model):
    char_field = models.CharField(max_length=100)
    text_field = models.TextField()
    boolean_field = models.BooleanField()
    integer_field = models.IntegerField()
    float_field = models.FloatField()
    decimal_field = models.DecimalField(max_digits=10, decimal_places=2)
    date_field = models.DateField()
    datetime_field = models.DateTimeField()
    email_field = models.EmailField()
    url_field = models.URLField()
    file_field = models.FileField(upload_to='uploads/')
    image_field = models.ImageField(upload_to='images/')
    class Meta:
        managed = False
        db_table = 'my_table_name'

trained/forms.py
from django import forms
from .models import *

class MenuForm(forms.ModelForm):
    class Meta:
        model = Menuss
        fields = ('name', 'answer')

from django import forms

from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = forms.ModelChoiceField(queryset=Menuss.objects.all())
    class Meta:
        model = Menuss
        fields = ('name', 'parent', 'answer')

       
from django import forms
from .models import Node

class NodeForm(forms.ModelForm):
    parent = forms.ModelChoiceField(queryset=Node.objects.all())

    class Meta:
        model = Node
        fields = ['name', 'parent','answer']
from django import forms
from .models import *

class PictureUploadForm(forms.ModelForm):
    class Meta:
        model = Admin_panel
        fields = ['heading','image','welcome_msg']

trained/views.py
from django.shortcuts import render,get_object_or_404
import re
from django.http import HttpRequest, JsonResponse
from django.shortcuts import render, HttpResponse,redirect
import random
import json
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from .models import *
import logging
from django.db import models
from django.core.management import call_command
from django.apps import apps
from .dynamic_models import *
from trained.dynamic_models import create_dynamic_model
from django.db import connection
from django.http import HttpResponse
from .models import *

# from .dynamic_models import create_dynamic_model
# def activity_logging(activity):
#     activity = activity
#     ip_address = request.META.get('REMOTE_ADDR')
#         if ip_address:
#             response = requests.get(f'https://api.ipgeolocation.io/ipgeo?apiKey=YOUR_API_KEY&ip={ip_address}')
#             if response.status_code == 200:
#                 location_data = response.json()
#                 location_info = f"{location_data['city']}, {location_data['country_name']}"
#                 location = location_info
#     activity_log = ActivityLog(activity=activity, ip_address=ip_address)


# This retrieves a Python logging instance (or creates it)
logger = logging.getLogger(__name__)
# Create your views here.
from django.shortcuts import render,redirect
# from .forms import *

def menu(request):
    if request.method == 'POST':
        form = NewCommentForm(request.POST)
        if form.is_valid():
            form.save() 
    else:
        form = NewCommentForm()

    return render(request, 'trained/train1.html', {'form': form})


from django.shortcuts import render
from .forms import *
from .models import *

def create_node(request):
    if request.method == 'POST':
        form = NodeForm(request.POST)
        if form.is_valid():
            form.save()
        data = Node.objects.all()
    else:
        form = NodeForm()
        data = Node.objects.all()

    nodes = Node.objects.all()
    context = {
        'form': form,
        'nodes': nodes,
        'data': data
    }
    return render(request, 'trained/train2.html', context)

def edit_menu(request, pk):
    book = get_object_or_404(Node, id=pk)
    form = NodeForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        # return redirect('/trained/')
     
    return render(request, 'trained/edit_menu.html', {'form': form, 'book': book})

def delete_menu(request, pk):
    my_object = get_object_or_404(Node, id=pk)

    if request.method == 'POST':
        # Delete the object
        my_object.delete()
        return redirect('/trained/')
    return render(request, 'trained/train2.html')

def train_chat(request):

    if request.method == 'POST':
        menu = request.POST.get('menu').lower()
        my_model_instance = Node(name=menu)
        my_model_instance.save()
        #print(menu)

    data  = Node.objects.filter(parent__isnull=True)
    context = {'data': data}
        
    return render(request, 'trained/train.html',context)

def my_view(request,pk):
    parent = Node.objects.get(id=pk)
    queryset = Node.objects.filter(parent__isnull=False, parent=parent)
    data = []
    for model in queryset:
        data.append(model.name)
    return JsonResponse(data, safe=False)

def add_submenu(request,pk):
    if request.method == 'POST':
        name = request.POST.get('name')
        answer = request.POST.get('answer')
        parent = Node.objects.get(id=pk)
        data = {
        'name': name,
        'answer': answer,
        'parent': parent,
        }
        my_object = Node.objects.create(**data)
    parent = Node.objects.get(id=pk)
    queryset = Node.objects.filter(parent__isnull=False, parent=parent)
    # data = []
    # for model in queryset:
    #     data.append(model.name)
    return render(request, 'trained/show.html',{'data': queryset})

# def train_chat(request):   
#     return render(request, 'trained/chatbot-trainer.html')
from django.shortcuts import render
from .forms import *

def upload_picture(request):
    if request.method == 'POST':
        form = PictureUploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            
    else:
        form = PictureUploadForm()
    
    my_model = Admin_panel.objects.first()
    return render(request, 'trained/index2.html', {'form': form})

from django.db import models

  # Define the DynamicModel at the module level

def user_register(request):
        if request.method == 'POST':
            input_types = {}
            column_names = []

            for field_name, field_value in request.POST.items():
                if field_name.endswith('_input_type'):
                    x = field_name.split('_')
                    field_name = x[0]  # Remove '_input_type' suffix

                    input_type = field_value
                    input_types[field_name] = input_type
                    column_names.append(field_name)
                    input_type = field_value
                    input_types[field_name] = input_type
                    my_object = user_panel.objects.create(input_label=field_name, input_type=input_type, parent_id=1)

            # Generate the CREATE TABLE SQL statement
            table_name = MyModel._meta.db_table
            columns = ', '.join([f"{column} VARCHAR(255)" for column in column_names])  # Modify the VARCHAR(255) to match your field types
            sql = f"CREATE TABLE {table_name} (id INT AUTO_INCREMENT PRIMARY KEY, {columns})"

            # Execute the SQL statement
            with connection.cursor() as cursor:
                cursor.execute(sql)

        return render(request, 'trained/user_register.html')

def show_query(request):
    my_view = user_panel.objects.filter(parent_id=1).order_by('-id')
    my_view = my_view.reverse()
    if request.method == 'POST':
        # Retrieve form data
        table_name = MyModel._meta.db_table
        form_data = {}
        with connection.cursor() as cursor:
            cursor.execute(f"DESCRIBE {table_name}")
            columns = [column[0] for column in cursor.fetchall()]
        for column in columns:
            value = request.POST.get(column, '')
            print(value)
            form_data[column] = value

        # Save form data to the dynamically created table
        with connection.cursor() as cursor:
            columns = ', '.join(form_data.keys())
            values = ', '.join([f"'{value}'" for value in form_data.values()])
            sql = f"INSERT INTO {table_name} ({columns}) VALUES ({values})"
            cursor.execute(sql)
        
    return render(request, 'trained/show_query.html', {'my_view': my_view})
    
def home(request):
    return render(request, 'new_folder/index.html')
def chatbot_view(request):
    return render(request, 'new_folder/chatbot.html')
def chatbot_details(request):
    return render(request, 'new_folder/chatbot_details.html')
def chatbot_trainer(request):
    return render(request, 'new_folder/chatbot_trainer.html')
def query_form(request):
    return render(request, 'new_folder/query_form.html')

trained/templates/trained/add_submenu.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<form method="POST">
    {%csrf_token%}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Name</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Answer</label>
    <input type="text" nmae = 'answer' class="form-control" id="exampleInputPassword1">
  </div>
 
  <input type="submit" value="Add submenu">
</form>

trained/templates/trained/edit_menu.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<form method="post" novalidate>
	{% csrf_token %}
	{{ form.as_p }}
    {{ form.my_field.errors }}
	<input type="submit" value="Save" />
</form>

trained/templates/trained/index2.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<!-- <button id="openButton">Open Text Box</button>
<div id="textBoxContainer"></div>

  



<script>
const openButton = document.getElementById('openButton');
const textBoxContainer = document.getElementById('textBoxContainer');

openButton.addEventListener('click', function() {
  // Create text box element
  const textBox = document.createElement('input');
  textBox.type = 'text';
  textBox.id = 'textBox';

  // Create submit button element
  const submitButton = document.createElement('button');
  submitButton.textContent = 'Submit';

  // Append text box and submit button to the container
  textBoxContainer.appendChild(textBox);
  textBoxContainer.appendChild(submitButton);

  // Add event listener to submit button
  submitButton.addEventListener('click', function() {
    const inputText = textBox.value;
    // Do something with the input text
    console.log(inputText);
  });
});



</script> -->

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
  

trained/templates/trained/show.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<form method="POST">
    {%csrf_token%}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Name</label>
    <input type="text" class="form-control" placeholder = "Enter the Submenu" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">
  </div>
  <!-- <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Answer</label>
    <input type="text" nmae = 'answer' class="form-control" id="exampleInputPassword1">
  </div>
  -->
  <input type="submit" value="Add submenu">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <style>
        .p-0 {
            padding: 0;
        }

        .m-0 {
            margin: 0;
        }

        .row {
            margin: 0;
            display: flex;
        }

        .container-fld {
            width: 1000px;
            margin: 0 auto;
        }

        .cont {
            width: 1000px;
            margin: 0 auto;
        }

        .pnl {
            margin-bottom: 20px;
            background-color: #fff;
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
            border-radius: 10px 10px 0 0;
        }

        .pnl-body {
            padding: 20px;
        }

        .pnl-header {
            text-align: center;
            padding: 5px 0px;
            /* background: linear-gradient(337deg, rgba(2, 0, 36, 1) 0%, rgba(14, 9, 121, 1) 43%, rgba(0, 212, 255, 1) 100%); */
            background: linear-gradient(357deg, rgba(73, 168, 203, 1) 0%, rgba(77, 181, 219, 1) 99%);
            color: #fff;
            border-radius: 10px 10px 0 0;
        }

        .pnl-heading {
            padding: 10px;
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        }

        .pnl-btn {
            font-size: inherit;
            cursor: pointer;
            font-weight: 600;
            transition: all 0.3s;
            background: linear-gradient(357deg, rgba(73, 168, 203, 1) 0%, rgba(77, 181, 219, 1) 99%);
            color: #fff;
            border: 2px solid;
            padding: 7px 20px;
            border-radius: 19px;
        }

        .pnl-btn-hov2:hover {
            color: rgb(46 71 163);
            background: #fff;
        }

        .pnl-btn-hov1:hover {
            transform: rotate(5deg) translate(-3px, 2px) scale(1, 1.1) skew(-4deg, -4deg);
            text-shadow: -7px 5px 0px rgb(255 255 255 / 30%);
        }

        .sub-menu {
            border-bottom: 1px solid;
            border-right: 1px solid;
            border-left: 1px solid;
            border-color: #dbdada;
        }

        .icon-stl:hover {
            top: -3px !important;
            position: relative;
        }

        a.pnl-btn {
            text-decoration: none;
        }

        .icon-stl {
            font-size: 20px;
            color: #fff;
            padding: 10px;
            box-sizing: border-box;
            transition: .9s;
        }

        .input_div {
            box-shadow: inset rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
            border: none;
            padding: 0px 0px 0px 10px;
            border-radius: 25px;
            display: flex;
            justify-content: space-between;
            box-shadow: inset rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px;

        }

        .input-field {
            border: none;
            background: none;
            width: 100%;
        }

        .input-field:focus-visible {
            outline: none;
        }

        .add-menu-btn {
            padding: 15px 30px;
            border-radius: 30px;
        }

        .side-bar {
            background: linear-gradient(357deg, rgba(73, 168, 203, 1) 0%, rgba(77, 181, 219, 1) 99%);
        }

        .drop-icon {
            float: right;
            font-size: 20px;
            cursor: pointer;
        }

        .overflow-y {
            overflow-y: scroll;
            height: 400px;
        }

        .action_icon_list {
            padding: 0;
            text-align: center;
            margin: 0;
        }

        .action_icons {
            list-style-type: none;
        }

        .list-items {
            display: none;
            color: #000;
            list-style-type: none;
        }

        .icon-stl:hover .list-items {
            display: block;
            visibility: visible;
            opacity: 1;
        }

        .list-items {
            padding: 0;
        }

        .dropdown li {
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
        }

        .list-name {
            padding: 15px 5px;
            font-size: 13px;
            cursor: pointer;
            font-weight: 600;
            line-height: 14px;
            text-transform: uppercase;
        }

        .input-trash {
            background: linear-gradient(357deg, rgba(73, 168, 203, 1) 0%, rgba(77, 181, 219, 1) 99%);
            border-radius: 78px;
            font-size: 13px;
            width: 32px;
            display: flex;
            justify-content: center;
        }

        .mb-1 {
            margin-bottom: 1rem;
        }

        .p-2 {
            padding: 2rem;
        }

        .text-align-right {
            text-align: right;
        }

        ul.drop-listt li {
            display: inline;
        }


        .my-drop {
            list-style-type: none;
            display: flex;
            padding: 0px;
            float: right;
        }

        ul.my-drop li {
            padding: 2px;
        }


        /* .dropdown {
	background: orange;
	visibility: hidden;
  opacity: 0;
  min-width: 5rem;
	position: absolute;
  transition: all 0.5s ease;
  margin-top: 1rem;
	left: 0;
  display: none;
} */

        .dropdown {
            background: orange;
            visibility: hidden;
            opacity: 0;
            min-width: 10rem;
            position: absolute;
            transition: all 0.5s ease;
            left: 38px;
            display: none;
            background: linear-gradient(357deg, rgba(73, 168, 203, 1) 0%, rgba(77, 181, 219, 1) 99%);
            color: #fff !important;
            list-style-type: none;
            padding: 0;
            text-align: center;
            border-radius: 5px;
            margin-top: 1px;
            z-index: 9;
        }

        .drop-li:hover .dropdown {
            visibility: visible;
            opacity: 1;
            display: block;
        }

        ul.dropdown li {
            padding: 10px;
        }

        ul.dropdown li a {
            color: #fff;
            font-weight: 600;
            text-transform: uppercase;
            text-decoration: none;
        }

        .align {
            align-self: center;
        }
    </style>
</head>

<body>


    <div class="container-fld">
        <div class="cont">
            <div class="col-md-12">
                <div class="pnl">
                    

                    <form class="form" method="POST" >
                        {%csrf_token%}
                        <!-- /***** Menu Button *******/ -->
                       

                        <div class="overflow-y">
                            <!-- /***** Side Bar with Menu name *******/ -->
                            <div class="pnl-inner-body">
                                <div class=" pnl-body row m-0">

                                    <div class=" col-md-12 p-0">
                                        {% for item in data %}
                                        <div class="pnl-heading row">
                                            <div class="col-md-10 align">
                                                <div id="pnl-lebel1" class="menu-name">{{item.name}}
                                                </div>
                                            </div>

                                            <div class="col-md-3 p-0 text-align-right">
                                                <ul class=" my-drop">
                                                    <li class="drop-li "><a href="#"></a>
                                                        <i class="fa fa-plus icon-stl input-trash"
                                                            aria-hidden="true"></i>
                                                        <ul class="dropdown">
                                                            <li><a href="{%url 'trained:add_submenu' item.id%}">Add Submenu</a></li>
                                                           
                                                        </ul>
                                                    <li><a href="{% url 'trained:edit_menu' item.id %}"><i
                                                                class="fa fa-pencil-square-o icon-stl input-trash"
                                                                aria-hidden="true"></i></a></li>
                                                    </li>
                                                    <li><a href="{% url 'trained:delete_menu' item.id %}"><i class="fa fa-trash icon-stl input-trash"
                                                                aria-hidden="true"></i></a></li>
                                                                
                                                                

                                                   
                                                </ul>
                                            </div>
                                        </div>
                                        {%endfor%}
                                                                                <!-- /******* Add Answer Field *******/ -->
                                       
                                        <!-- /******* Add Answer Field *******/ -->
                                    </div>
                                </div>
                                <!-- /***** Side Bar with Menu name *******/ -->

                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

   



    <!-- <script>
        function show_hide() {
            var click = document.getElementById("list-items");
            if (click.style.display === "none") {
                click.style.display = "block";
            } else {
                click.style.display = "none";
            }
        }
    </script> -->



</body>

</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
    $('.filter-link').click(function(e) {
        e.preventDefault();
        
        var id = $(this).data('id');
        alter(id)

        $.ajax({
            url: '/my_view/' + id + '/',
            method: 'GET',
            success: function(response) {
          var options = response.options;
          var dropdown = $('#my-dropdown');
          
          // Clear previous options
          dropdown.empty();
          
          // Generate dropdown options dynamically
          for (var i = 0; i < options.length; i++) {
            var option = $('<option>').val(options[i]).text(options[i]);
            dropdown.append(option);
          }
        }
     
        });
    });
});
</script>

trained/templates/trained/train2.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<form method="post" action="">
    {% csrf_token %}
    <label for="{{ form.name.id_for_label }}">Name:</label>
    {{ form.name }}
    <label for="{{ form.parent.id_for_label }}">Answer:</label>
    {{ form.answer }}
    <label for="{{ form.parent.id_for_label }}">Parent:</label>
    {{ form.parent }}

    <input type="submit" value="Submit">
</form>
{% if data %}

          <div class="row my-2 mx-1 justify-content-center">
            <table class="table table-striped table-borderless">
              <thead style="background-color:#84B0CA ;" class="text-white">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Name</th>
                  <th scope="col">Answer</th>
                  <th scope="col">parent</th>
                  <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
                {% for item in data %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.answer }}</td>
                <td>{{ item.parent }}</td>
                <td><a href="{% url 'trained:edit_menu' item.id %}">Edit</a></td>
                <td><a href="{% url 'trained:delete_menu' item.id %}">Delete</a></td>
            </tr>
        {% endfor %}
                
                
              </tbody>
  
            </table>
          </div>
          
          
        </div>
      </div>
    </div>
  </div>
{% endif %}